### ISSUE TITLE
Build centos 8 package

### ISSUE THREAD

**Issue by rgarcia89** [sensu-plugins/sensu-plugins-kubernetes#112]
Currently there are only packages for centos 6 and 7...

**Comment by miralgj** [comment]
Was able to use it on RHEL 8 by adding a new filter to the asset definition and re-using the RHEL 7 asset.

```
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    - entity.system.platform_family == 'rhel'
    - entity.system.platform_version.split('.')[0] == '8'
    headers: null
    sha512: edc2ff21ece24ba83523b1986029a851b06f5733d47ef8e79b261a9999415ea0cc4e3729e84f88e178f5aea9841c1db232313f512c990f608f728cd1b80ebfa4
    url: https://assets.bonsai.sensu.io/a82804509e76a1e1dd20658e98def777707d8165/sensu-plugins-kubernetes_5.0.2_centos7_linux_amd64.tar.gz
```
